apiVersion: v1
kind: Service
metadata:
  name: cicd-demo-app
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: cicd-demo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http